### ISSUE TITLE
Monkeypatching Fixnum.blank? is causing problems with ActiveRecord

### ISSUE THREAD

**Issue by Hadescho** [mephux/ruby-nessus#34]
The [monkeypatch on Fixnum](https://github.com/mephux/ruby-nessus/blob/c43cc0087e7678fd84fea227d4d21d0b6b4cd4bc/lib/ruby-nessus/core_ext/helpers.rb#L8-l14) is introducing problems with ActiveRecord, or to be more precise with the presence validations.

Since the presence validation is using ```Object#blank?```, if you have record with Fixnum, and it's value can be zero, it may cause the validation to fail false-positively.

Possible temporary solution is to switch from presence validation to inclusion validation, for the fields where the problem might arise:

```Ruby
# you can change:
validates :score, presence: true
# to:
validates :score, inclusion: (0..5)
# or if there isn't valid range of values
validates :score, inclusion: (-Float::INFINITY..Float::INFINITY)
```

I might make a pull request this weekend, but I can't promise anything.

**Comment by mephux** [comment]
@Hadescho thanks
